Fornecedores/Models/IndexRegiao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fornecedores.Models
{
    public class IndexRegiao
    {
        public IList<DAL.Fornecedor> Fornecedores { get; set; }
        public IList<RegiaoEstado> RegioesEstado { get; set; }
        public IList<DAL.Estado> Estados { get; set; }
        public long? IdFornecedor { get; set; }

        public int IdEstado { get; set; }      
        public string DescricaoRegiao { get; set; }

    }
     
}

Fornecedores/Models/RegiaoEstado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fornecedores.Models
{
    public class RegiaoEstado
    {
        public long IdRegiao { get; set; }
        public int IdEstado { get; set; }
        public long IdFornecedorFormulario { get; set; }        
        public string DescricaoRegiao { get; set; }
        public byte Ativo { get; set; }
        public string DescricaoEstado { get; set; }
        public bool relacionadoComFornecedor { get; set; }


    }
}

Fornecedores/Models/RegiaoView.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fornecedores.Models
{
    public class RegiaoView
    {
        public long IdRegiao { get; set; }

        public string Descricao { get; set; }
        public byte Ativo { get; set; }
        public int IdEstado { get; set; }

        public virtual Estado EstadoRegiao { get; set; }
        public IList<DAL.Estado> Estados { get; set; }
    }
}

Fornecedores/Controllers/RegiaoController.cs
using DAL;
using Fornecedores.DAO;
using Fornecedores.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Fornecedores.Controllers
{
    public class RegiaoController : Controller
    {
        RegiaoDAO regiaoDAO = new RegiaoDAO();
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        EstadoDAO estadoDAO = new EstadoDAO();

        // GET: Regiao
        public ActionResult Index(IndexRegiao model)
        {
            model.Fornecedores = fornecedorDAO.ListaFornecedores();
            model.RegioesEstado = regiaoDAO.ListaRegioesEstado(model.IdFornecedor,Constantes.OPCAO_INDEX);
            return View(model);
        }

                
        public ActionResult CadastroRegiao(IndexRegiao model)
        {
            model.Estados = estadoDAO.ListaEstados();
            model.RegioesEstado = regiaoDAO.ListaRegioesEstado(0, Constantes.OPCAO_CADASTRO_REGIAO);
            return View(model);
        }

        public ActionResult Adiciona(IndexRegiao indexRegiao)
        {
            if (ModelState.IsValid)
            {
                regiaoDAO.Adiciona(indexRegiao);
                ModelState.AddModelError("", "Error in cloud - GetPLUInfo");
                return RedirectToAction("CadastroRegiao");                            
            }
            else
            {
                ModelState.AddModelError("", "Error in cloud - GetPLUInfo");
                return RedirectToAction("CadastroRegiao");
            }

        }

        public ActionResult Editar(int? IdRegiao)
        {
            if (IdRegiao == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RegiaoView regiaoView = regiaoDAO.GetRegiaoById(IdRegiao);
            regiaoView.Estados = estadoDAO.ListaEstados();

            if (regiaoView == null)
            {
                return HttpNotFound();
            }
            return View(regiaoView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "IdRegiao,Descricao,Ativo,IdEstado")] RegiaoView regiaoView)
        {
            if (ModelState.IsValid)
            {
                regiaoDAO.atualizaRegiao(regiaoView);
                return RedirectToAction("CadastroRegiao");
            }
            return View(regiaoView);
        }


        public ActionResult Inativar(int? IdRegiao)
            {
                if (IdRegiao == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

            regiaoDAO.InativarRegiao(IdRegiao);
               
                return RedirectToAction("CadastroRegiao");
            }

        public ActionResult Ativar(int? IdRegiao)
        {
            if (IdRegiao == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            regiaoDAO.AtivarRegiao(IdRegiao);

            return RedirectToAction("CadastroRegiao");
        }

    }
}

Fornecedores/Views/Regiao/CadastroRegiao.cshtml
@model Fornecedores.Models.IndexRegiao

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="style.css">
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script> 
    
        <script type="text/javascript">
            $(document).ready(function() {
                $("#SubmitProject").click(function () {
                    if ($("#Validatetextbox").val() == "") {
                        alert("Informe um valor para continuar");
                    }
                });
    });
    </script>  
    
</head>
<body>
    <div class="container">
        <div class="divBack">
            <strong>Cadastro de Regiões</strong>
        </div>
        @using (Html.BeginForm("Adiciona", "Regiao", FormMethod.Post))
        {
            <div class="form">
                <div>
                    <span id="estado">@Html.LabelFor(m => m.IdEstado, "Estado")</span><span class="obrigatorio">*</span>
                    <div class="select">
                        @Html.DropDownListFor(m => m.IdEstado, new SelectList(Model.Estados, "IdEstado", "Descricao"), "Selecione")
                    </div>
                </div>
                <div class="espacamento-vert">
                    <span id="descricaoRegiao">@Html.LabelFor(m => m.DescricaoRegiao, "Regiao:")</span><span class="obrigatorio">*</span>                           

                    <div class="input">
                        @Html.TextBoxFor(m => m.DescricaoRegiao, new { @class = "form-control", @id = "Validatetextbox" })
                    </div>
                </div>
                <div class="espacamento-vert">
                  
                    <input type="submit" class = "btn btn-primary" valor="Inserir" id="SubmitProject" />
                    
                    <p id="error"></p>
                </div>
                <h3> *Valores repetidos não serão adicionados </h3>
            </div>
        }


        <div class="grid">
            <table>
                <thead>
                    <tr>
                        <th>UF</th>
                        <th>Região</th>
                        <th>Situação</th>
                        <th colspan="2">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var regiaoEstado in Model.RegioesEstado)
                    {
                        <tr>
                            <td>@regiaoEstado.DescricaoEstado</td>
                            <td>@regiaoEstado.DescricaoRegiao</td>

                            @if (regiaoEstado.Ativo == 1)
                            {
                                <td>Ativo</td>
                            }
                            else
                            {
                                <td><p style="color:red;">Inativo</p></td>
                            }

                            <td>
                                @Html.ActionLink("Editar", "Editar", new { IdRegiao = regiaoEstado.IdRegiao }) |

                                @if (regiaoEstado.Ativo == 1)
                                {
                                    @Html.ActionLink("Inativar", "Inativar", new { IdRegiao = regiaoEstado.IdRegiao })
                                }
                                else
                                {
                                    @Html.ActionLink("Ativar", "Ativar", new { IdRegiao = regiaoEstado.IdRegiao })
                                }

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</body>
</html>

Fornecedores/Views/Regiao/Editar.cshtml
@model Fornecedores.Models.RegiaoView

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Região</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Região</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdRegiao)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

   

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ativo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
            </div>
        </div>

     
            <div class="form-group">
                @Html.LabelFor(m => m.IdEstado, "Estado", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                   
                    @Html.DropDownListFor(m => m.IdEstado, new SelectList(Model.Estados, "IdEstado", "Descricao"), "Selecione", new { @class = "form-control" })
                </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save"  class = "btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para Lista", "CadastroRegiao")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Fornecedores/Views/Regiao/Index.cshtml
@model Fornecedores.Models.IndexRegiao

<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="style.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

</head>
<body>

    <div class="container">
        <div class="divBack">
            <strong>Cadastro de Regiões do Fornecedor</strong>
        </div>

        @using (Html.BeginForm("Index", "Regiao", FormMethod.Get))
        {
            @Html.LabelFor(m => m.IdFornecedor, "Fornecedor")
            @Html.DropDownListFor(m => m.IdFornecedor, new SelectList(Model.Fornecedores, "IdFornecedor", "Nome"), "Selecione")

            <input type="submit" value="Buscar" />
        }

        
        <div class="grid">
            <table>

                <thead>
                    <tr>
                        <th><input type="checkbox" /></th>
                        <th>UF</th>
                        <th>Regiao</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var regiaoEstado in Model.RegioesEstado)
                    {

                        if (regiaoEstado.Ativo == 1)
                        {
                            <tr>
                                <td>
                                    <input @(Convert.ToBoolean(regiaoEstado.relacionadoComFornecedor) == true ? "checked='checked'" : string.Empty) type="checkbox" />
                                </td>
                                <td>@regiaoEstado.DescricaoEstado</td>
                                <td>@regiaoEstado.DescricaoRegiao</td>
                            </tr>
                        }
                        else
                        {
                            <tr bgcolor="red">
                                <td>
                                    <input @(Convert.ToBoolean(regiaoEstado.relacionadoComFornecedor) == true ? "checked='checked'" : string.Empty) type="checkbox" />
                                </td>
                                <td>@regiaoEstado.DescricaoEstado</td>
                                <td>@regiaoEstado.DescricaoRegiao</td>
                            </tr>

                        }



                    }

                </tbody>


            </table>
        </div>
        <div class="espacamento-vert">
            <input type="submit" value="Gravar" />
        </div>



    </div>
</body>
</html>

Fornecedores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
   

    <div class="container">
        <main class="col-sm-8">
            @RenderBody()
        </main>
        <aside class="col-sm-4">
            <h3>Acesso Rápido</h3>
            <ul>
                <li>@Html.ActionLink("Cadastro de Regiões", "CadastroRegiao", "Regiao")</li>
                <li>@Html.ActionLink("Cadastro de Regiões De Fornecedores", "Index", "Regiao")</li>
            </ul>
        </aside>

        <hr />
     
    </div>

    <footer class="container">
        <p class="col-sm-4">     &copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>